import { Product, Category } from "@ascend/shared";

export const categories: Category[] = [
  { id: "1", name: "T-Shirts", slug: "t-shirts", description: "Premium oversized tees", image_url: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600" },
  { id: "2", name: "Hoodies", slug: "hoodies", description: "Comfortable hoodies", image_url: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600" },
  { id: "3", name: "Cargos", slug: "cargos", description: "Streetwear cargos", image_url: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600" },
  { id: "4", name: "Accessories", slug: "accessories", description: "Complete your look", image_url: "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=600" },
  { id: "5", name: "Jackets", slug: "jackets", description: "Outerwear essentials", image_url: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600" },
  { id: "6", name: "Bottoms", slug: "bottoms", description: "Pants & shorts", image_url: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600" },
  { id: "7", name: "Headwear", slug: "headwear", description: "Caps, beanies & more", image_url: "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=600" },
  { id: "8", name: "Bags", slug: "bags", description: "Backpacks & totes", image_url: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600" },
];

export const products: Product[] = [
  // T-SHIRTS (8 products)
  {
    id: "1",
    name: "Essential Oversized Tee",
    slug: "essential-oversized-tee",
    description: "Premium cotton oversized t-shirt with a relaxed fit. Features dropped shoulders and a longer body length for that perfect streetwear look.",
    price: 2499,
    compare_at_price: 2999,
    sku: "ASC-TS-001",
    is_active: true,
    category_id: "1",
    category: categories[0],
    images: [
      { id: "1", product_id: "1", url: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600", alt_text: "Essential Oversized Tee", sort_order: 0, is_primary: true },
      { id: "2", product_id: "1", url: "https://images.unsplash.com/photo-1622445275576-721325763afe?w=600", alt_text: "Essential Oversized Tee Back", sort_order: 1, is_primary: false },
    ],
    variants: [
      { id: "1", product_id: "1", size: "S", color: "Black", sku: "ASC-TS-001-BK-S", price_adjustment: 0, stock: 10, is_active: true },
      { id: "2", product_id: "1", size: "M", color: "Black", sku: "ASC-TS-001-BK-M", price_adjustment: 0, stock: 15, is_active: true },
      { id: "3", product_id: "1", size: "L", color: "Black", sku: "ASC-TS-001-BK-L", price_adjustment: 0, stock: 12, is_active: true },
      { id: "4", product_id: "1", size: "XL", color: "Black", sku: "ASC-TS-001-BK-XL", price_adjustment: 0, stock: 8, is_active: true },
      { id: "5", product_id: "1", size: "S", color: "White", sku: "ASC-TS-001-WH-S", price_adjustment: 0, stock: 10, is_active: true },
      { id: "6", product_id: "1", size: "M", color: "White", sku: "ASC-TS-001-WH-M", price_adjustment: 0, stock: 14, is_active: true },
      { id: "7", product_id: "1", size: "L", color: "White", sku: "ASC-TS-001-WH-L", price_adjustment: 0, stock: 11, is_active: true },
      { id: "8", product_id: "1", size: "XL", color: "White", sku: "ASC-TS-001-WH-XL", price_adjustment: 0, stock: 7, is_active: true },
      { id: "9", product_id: "1", size: "S", color: "Grey", sku: "ASC-TS-001-GY-S", price_adjustment: 0, stock: 9, is_active: true },
      { id: "10", product_id: "1", size: "M", color: "Grey", sku: "ASC-TS-001-GY-M", price_adjustment: 0, stock: 13, is_active: true },
      { id: "11", product_id: "1", size: "L", color: "Grey", sku: "ASC-TS-001-GY-L", price_adjustment: 0, stock: 10, is_active: true },
      { id: "12", product_id: "1", size: "XL", color: "Grey", sku: "ASC-TS-001-GY-XL", price_adjustment: 0, stock: 6, is_active: true },
    ],
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "2",
    name: "Heavyweight Hoodie",
    slug: "heavyweight-hoodie",
    description: "Ultra-premium 450gsm cotton fleece hoodie. Features a double-layered hood, kangaroo pocket, and ribbed cuffs. The ultimate streetwear essential.",
    price: 4999,
    compare_at_price: 5999,
    sku: "ASC-HD-001",
    is_active: true,
    category_id: "2",
    category: categories[1],
    images: [
      { id: "3", product_id: "2", url: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600", alt_text: "Heavyweight Hoodie", sort_order: 0, is_primary: true },
      { id: "4", product_id: "2", url: "https://images.unsplash.com/photo-1578681994506-b8f463449011?w=600", alt_text: "Heavyweight Hoodie Back", sort_order: 1, is_primary: false },
    ],
    variants: [
      { id: "13", product_id: "2", size: "S", color: "Black", sku: "ASC-HD-001-BK-S", price_adjustment: 0, stock: 8, is_active: true },
      { id: "14", product_id: "2", size: "M", color: "Black", sku: "ASC-HD-001-BK-M", price_adjustment: 0, stock: 12, is_active: true },
      { id: "15", product_id: "2", size: "L", color: "Black", sku: "ASC-HD-001-BK-L", price_adjustment: 0, stock: 10, is_active: true },
      { id: "16", product_id: "2", size: "XL", color: "Black", sku: "ASC-HD-001-BK-XL", price_adjustment: 0, stock: 6, is_active: true },
      { id: "17", product_id: "2", size: "S", color: "Charcoal", sku: "ASC-HD-001-CH-S", price_adjustment: 0, stock: 7, is_active: true },
      { id: "18", product_id: "2", size: "M", color: "Charcoal", sku: "ASC-HD-001-CH-M", price_adjustment: 0, stock: 11, is_active: true },
      { id: "19", product_id: "2", size: "L", color: "Charcoal", sku: "ASC-HD-001-CH-L", price_adjustment: 0, stock: 9, is_active: true },
      { id: "20", product_id: "2", size: "XL", color: "Charcoal", sku: "ASC-HD-001-CH-XL", price_adjustment: 0, stock: 5, is_active: true },
    ],
    created_at: "2024-01-02T00:00:00Z",
    updated_at: "2024-01-02T00:00:00Z",
  },
  {
    id: "3",
    name: "Cargo pants",
    slug: "cargo-pants",
    description: "Technical cargo pants with 8 pockets. Made from water-resistant nylon blend with articulated knees for maximum mobility.",
    price: 3999,
    compare_at_price: 4499,
    sku: "ASC-CG-001",
    is_active: true,
    category_id: "3",
    category: categories[2],
    images: [
      { id: "5", product_id: "3", url: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600", alt_text: "Cargo Pants", sort_order: 0, is_primary: true },
      { id: "6", product_id: "3", url: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600", alt_text: "Cargo Pants Detail", sort_order: 1, is_primary: false },
    ],
    variants: [
      { id: "21", product_id: "3", size: "30", color: "Black", sku: "ASC-CG-001-BK-30", price_adjustment: 0, stock: 6, is_active: true },
      { id: "22", product_id: "3", size: "32", color: "Black", sku: "ASC-CG-001-BK-32", price_adjustment: 0, stock: 10, is_active: true },
      { id: "23", product_id: "3", size: "34", color: "Black", sku: "ASC-CG-001-BK-34", price_adjustment: 0, stock: 8, is_active: true },
      { id: "24", product_id: "3", size: "36", color: "Black", sku: "ASC-CG-001-BK-36", price_adjustment: 0, stock: 5, is_active: true },
      { id: "25", product_id: "3", size: "30", color: "Olive", sku: "ASC-CG-001-OL-30", price_adjustment: 0, stock: 7, is_active: true },
      { id: "26", product_id: "3", size: "32", color: "Olive", sku: "ASC-CG-001-OL-32", price_adjustment: 0, stock: 9, is_active: true },
      { id: "27", product_id: "3", size: "34", color: "Olive", sku: "ASC-CG-001-OL-34", price_adjustment: 0, stock: 6, is_active: true },
      { id: "28", product_id: "3", size: "36", color: "Olive", sku: "ASC-CG-001-OL-36", price_adjustment: 0, stock: 4, is_active: true },
    ],
    created_at: "2024-01-03T00:00:00Z",
    updated_at: "2024-01-03T00:00:00Z",
  },
  {
    id: "4",
    name: "Logo Cap",
    slug: "logo-cap",
    description: "Premium 6-panel structured cap with embroidered logo. Adjustable strap with metal buckle.",
    price: 1299,
    compare_at_price: 1499,
    sku: "ASC-AC-001",
    is_active: true,
    category_id: "4",
    category: categories[3],
    images: [
      { id: "7", product_id: "4", url: "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=600", alt_text: "Logo Cap", sort_order: 0, is_primary: true },
    ],
    variants: [
      { id: "29", product_id: "4", size: "One Size", color: "Black", sku: "ASC-AC-001-BK-OS", price_adjustment: 0, stock: 20, is_active: true },
      { id: "30", product_id: "4", size: "One Size", color: "White", sku: "ASC-AC-001-WH-OS", price_adjustment: 0, stock: 18, is_active: true },
      { id: "31", product_id: "4", size: "One Size", color: "Navy", sku: "ASC-AC-001-NV-OS", price_adjustment: 0, stock: 15, is_active: true },
    ],
    created_at: "2024-01-04T00:00:00Z",
    updated_at: "2024-01-04T00:00:00Z",
  },
  {
    id: "5",
    name: "Graphic Print Tee",
    slug: "graphic-print-tee",
    description: "Oversized t-shirt with high-quality screen print graphics. 100% organic cotton with a relaxed drop-shoulder fit.",
    price: 2799,
    compare_at_price: 3299,
    sku: "ASC-TS-002",
    is_active: true,
    category_id: "1",
    category: categories[0],
    images: [
      { id: "8", product_id: "5", url: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600", alt_text: "Graphic Print Tee", sort_order: 0, is_primary: true },
    ],
    variants: [
      { id: "32", product_id: "5", size: "S", color: "Black", sku: "ASC-TS-002-BK-S", price_adjustment: 0, stock: 8, is_active: true },
      { id: "33", product_id: "5", size: "M", color: "Black", sku: "ASC-TS-002-BK-M", price_adjustment: 0, stock: 12, is_active: true },
      { id: "34", product_id: "5", size: "L", color: "Black", sku: "ASC-TS-002-BK-L", price_adjustment: 0, stock: 10, is_active: true },
      { id: "35", product_id: "5", size: "XL", color: "Black", sku: "ASC-TS-002-BK-XL", price_adjustment: 0, stock: 6, is_active: true },
    ],
    created_at: "2024-01-05T00:00:00Z",
    updated_at: "2024-01-05T00:00:00Z",
  },
  {
    id: "6",
    name: "Zip-Up Hoodie",
    slug: "zip-up-hoodie",
    description: "Full-zip heavyweight hoodie with side pockets. Perfect for layering in any season.",
    price: 5499,
    compare_at_price: 6499,
    sku: "ASC-HD-002",
    is_active: true,
    category_id: "2",
    category: categories[1],
    images: [
      { id: "9", product_id: "6", url: "https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=600", alt_text: "Zip-Up Hoodie", sort_order: 0, is_primary: true },
    ],
    variants: [
      { id: "36", product_id: "6", size: "S", color: "Black", sku: "ASC-HD-002-BK-S", price_adjustment: 0, stock: 5, is_active: true },
      { id: "37", product_id: "6", size: "M", color: "Black", sku: "ASC-HD-002-BK-M", price_adjustment: 0, stock: 8, is_active: true },
      { id: "38", product_id: "6", size: "L", color: "Black", sku: "ASC-HD-002-BK-L", price_adjustment: 0, stock: 7, is_active: true },
      { id: "39", product_id: "6", size: "XL", color: "Black", sku: "ASC-HD-002-BK-XL", price_adjustment: 0, stock: 4, is_active: true },
    ],
    created_at: "2024-01-06T00:00:00Z",
    updated_at: "2024-01-06T00:00:00Z",
  },
  {
    id: "7",
    name: "Tech Cargo Shorts",
    slug: "tech-cargo-shorts",
    description: "Above-knee length cargo shorts with 6 pockets. Quick-dry nylon blend material.",
    price: 2499,
    compare_at_price: 2999,
    sku: "ASC-CG-002",
    is_active: true,
    category_id: "3",
    category: categories[2],
    images: [
      { id: "10", product_id: "7", url: "https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=600", alt_text: "Tech Cargo Shorts", sort_order: 0, is_primary: true },
    ],
    variants: [
      { id: "40", product_id: "7", size: "30", color: "Black", sku: "ASC-CG-002-BK-30", price_adjustment: 0, stock: 10, is_active: true },
      { id: "41", product_id: "7", size: "32", color: "Black", sku: "ASC-CG-002-BK-32", price_adjustment: 0, stock: 12, is_active: true },
      { id: "42", product_id: "7", size: "34", color: "Black", sku: "ASC-CG-002-BK-34", price_adjustment: 0, stock: 8, is_active: true },
      { id: "43", product_id: "7", size: "36", color: "Black", sku: "ASC-CG-002-BK-36", price_adjustment: 0, stock: 5, is_active: true },
    ],
    created_at: "2024-01-07T00:00:00Z",
    updated_at: "2024-01-07T00:00:00Z",
  },
  {
    id: "8",
    name: "Crossbody Bag",
    slug: "crossbody-bag",
    description: "Compact crossbody bag with adjustable strap. Multiple compartments for essentials.",
    price: 1999,
    compare_at_price: 2499,
    sku: "ASC-AC-002",
    is_active: true,
    category_id: "4",
    category: categories[3],
    images: [
      { id: "11", product_id: "8", url: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600", alt_text: "Crossbody Bag", sort_order: 0, is_primary: true },
    ],
    variants: [
      { id: "44", product_id: "8", size: "One Size", color: "Black", sku: "ASC-AC-002-BK-OS", price_adjustment: 0, stock: 15, is_active: true },
      { id: "45", product_id: "8", size: "One Size", color: "Tan", sku: "ASC-AC-002-TN-OS", price_adjustment: 0, stock: 12, is_active: true },
    ],
    created_at: "2024-01-08T00:00:00Z",
    updated_at: "2024-01-08T00:00:00Z",
  },
  // NEW PRODUCTS - T-SHIRTS
  {
    id: "9",
    name: "Vintage Washed Tee",
    slug: "vintage-washed-tee",
    description: "Pre-washed for that perfectly broken-in feel. Features a relaxed boxy fit with raw hem detailing.",
    price: 2199,
    compare_at_price: 2699,
    sku: "ASC-TS-003",
    is_active: true,
    category_id: "1",
    category: categories[0],
    images: [
      { id: "100", product_id: "9", url: "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=600", alt_text: "Vintage Washed Tee", sort_order: 0, is_primary: true },
    ],
    variants: [
      { id: "46", product_id: "9", size: "S", color: "Washed Blue", sku: "ASC-TS-003-WB-S", price_adjustment: 0, stock: 12, is_active: true },
      { id: "47", product_id: "9", size: "M", color: "Washed Blue", sku: "ASC-TS-003-WB-M", price_adjustment: 0, stock: 15, is_active: true },
      { id: "48", product_id: "9", size: "L", color: "Washed Blue", sku: "ASC-TS-003-WB-L", price_adjustment: 0, stock: 10, is_active: true },
      { id: "49", product_id: "9", size: "XL", color: "Washed Blue", sku: "ASC-TS-003-WB-XL", price_adjustment: 0, stock: 8, is_active: true },
    ],
    created_at: "2024-02-01T00:00:00Z",
    updated_at: "2024-02-01T00:00:00Z",
  },
  {
    id: "10",
    name: "Striped Rugby Tee",
    slug: "striped-rugby-tee",
    description: "Classic rugby-style striped tee with contrast collar. Heavyweight cotton construction.",
    price: 2999,
    compare_at_price: 3499,
    sku: "ASC-TS-004",
    is_active: true,
    category_id: "1",
    category: categories[0],
    images: [
      { id: "101", product_id: "10", url: "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=600", alt_text: "Striped Rugby Tee", sort_order: 0, is_primary: true },
    ],
    variants: [
      { id: "50", product_id: "10", size: "S", color: "Black/White", sku: "ASC-TS-004-BW-S", price_adjustment: 0, stock: 8, is_active: true },
      { id: "51", product_id: "10", size: "M", color: "Black/White", sku: "ASC-TS-004-BW-M", price_adjustment: 0, stock: 10, is_active: true },
      { id: "52", product_id: "10", size: "L", color: "Black/White", sku: "ASC-TS-004-BW-L", price_adjustment: 0, stock: 6, is_active: true },
      { id: "53", product_id: "10", size: "XL", color: "Black/White", sku: "ASC-TS-004-BW-XL", price_adjustment: 0, stock: 4, is_active: true },
    ],
    created_at: "2024-02-02T00:00:00Z",
    updated_at: "2024-02-02T00:00:00Z",
  },
  {
    id: "11",
    name: "Pocket Logo Tee",
    slug: "pocket-logo-tee",
    description: "Minimalist tee with embroidered logo on chest pocket. Essential everyday staple.",
    price: 1799,
    compare_at_price: 2199,
    sku: "ASC-TS-005",
    is_active: true,
    category_id: "1",
    category: categories[0],
    images: [
      { id: "102", product_id: "11", url: "https://images.unsplash.com/photo-1562157873-818bc0726f68?w=600", alt_text: "Pocket Logo Tee", sort_order: 0, is_primary: true },
    ],
    variants: [
      { id: "54", product_id: "11", size: "S", color: "White", sku: "ASC-TS-005-WH-S", price_adjustment: 0, stock: 20, is_active: true },
      { id: "55", product_id: "11", size: "M", color: "White", sku: "ASC-TS-005-WH-M", price_adjustment: 0, stock: 25, is_active: true },
      { id: "56", product_id: "11", size: "L", color: "White", sku: "ASC-TS-005-WH-L", price_adjustment: 0, stock: 18, is_active: true },
      { id: "57", product_id: "11", size: "XL", color: "White", sku: "ASC-TS-005-WH-XL", price_adjustment: 0, stock: 12, is_active: true },
    ],
    created_at: "2024-02-03T00:00:00Z",
    updated_at: "2024-02-03T00:00:00Z",
  },
  // NEW PRODUCTS - HOODIES
  {
    id: "12",
    name: "Essential Pullover Hoodie",
    slug: "essential-pullover-hoodie",
    description: "Classic pullover hoodie with embroidered logo. Premium 380gsm cotton fleece.",
    price: 4499,
    compare_at_price: 5299,
    sku: "ASC-HD-003",
    is_active: true,
    category_id: "2",
    category: categories[1],
    images: [
      { id: "103", product_id: "12", url: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=600", alt_text: "Essential Pullover Hoodie", sort_order: 0, is_primary: true },
    ],
    variants: [
      { id: "58", product_id: "12", size: "S", color: "Black", sku: "ASC-HD-003-BK-S", price_adjustment: 0, stock: 10, is_active: true },
      { id: "59", product_id: "12", size: "M", color: "Black", sku: "ASC-HD-003-BK-M", price_adjustment: 0, stock: 14, is_active: true },
      { id: "60", product_id: "12", size: "L", color: "Black", sku: "ASC-HD-003-BK-L", price_adjustment: 0, stock: 12, is_active: true },
      { id: "61", product_id: "12", size: "XL", color: "Black", sku: "ASC-HD-003-BK-XL", price_adjustment: 0, stock: 8, is_active: true },
      { id: "62", product_id: "12", size: "S", color: "Grey", sku: "ASC-HD-003-GY-S", price_adjustment: 0, stock: 8, is_active: true },
      { id: "63", product_id: "12", size: "M", color: "Grey", sku: "ASC-HD-003-GY-M", price_adjustment: 0, stock: 12, is_active: true },
      { id: "64", product_id: "12", size: "L", color: "Grey", sku: "ASC-HD-003-GY-L", price_adjustment: 0, stock: 10, is_active: true },
      { id: "65", product_id: "12", size: "XL", color: "Grey", sku: "ASC-HD-003-GY-XL", price_adjustment: 0, stock: 6, is_active: true },
    ],
    created_at: "2024-02-04T00:00:00Z",
    updated_at: "2024-02-04T00:00:00Z",
  },
  {
    id: "13",
    name: "Graphic Print Hoodie",
    slug: "graphic-print-hoodie",
    description: "Oversized hoodie with all-over print design. Made for those who want to stand out.",
    price: 5999,
    compare_at_price: 6999,
    sku: "ASC-HD-004",
    is_active: true,
    category_id: "2",
    category: categories[1],
    images: [
      { id: "104", product_id: "13", url: "https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?w=600", alt_text: "Graphic Print Hoodie", sort_order: 0, is_primary: true },
    ],
    variants: [
      { id: "66", product_id: "13", size: "S", color: "Black", sku: "ASC-HD-004-BK-S", price_adjustment: 0, stock: 6, is_active: true },
      { id: "67", product_id: "13", size: "M", color: "Black", sku: "ASC-HD-004-BK-M", price_adjustment: 0, stock: 8, is_active: true },
      { id: "68", product_id: "13", size: "L", color: "Black", sku: "ASC-HD-004-BK-L", price_adjustment: 0, stock: 5, is_active: true },
      { id: "69", product_id: "13", size: "XL", color: "Black", sku: "ASC-HD-004-BK-XL", price_adjustment: 0, stock: 3, is_active: true },
    ],
    created_at: "2024-02-05T00:00:00Z",
    updated_at: "2024-02-05T00:00:00Z",
  },
  // NEW PRODUCTS - CARGOS & BOTTOMS
  {
    id: "14",
    name: "Slim Cargo Jeans",
    slug: "slim-cargo-jeans",
    description: "Modern slim-fit cargo jeans with stretch comfort. Features multiple utility pockets.",
    price: 4599,
    compare_at_price: 5299,
    sku: "ASC-BT-001",
    is_active: true,
    category_id: "6",
    category: categories[5],
    images: [
      { id: "105", product_id: "14", url: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=600", alt_text: "Slim Cargo Jeans", sort_order: 0, is_primary: true },
    ],
    variants: [
      { id: "70", product_id: "14", size: "30", color: "Dark Wash", sku: "ASC-BT-001-DW-30", price_adjustment: 0, stock: 8, is_active: true },
      { id: "71", product_id: "14", size: "32", color: "Dark Wash", sku: "ASC-BT-001-DW-32", price_adjustment: 0, stock: 12, is_active: true },
      { id: "72", product_id: "14", size: "34", color: "Dark Wash", sku: "ASC-BT-001-DW-34", price_adjustment: 0, stock: 10, is_active: true },
      { id: "73", product_id: "14", size: "36", color: "Dark Wash", sku: "ASC-BT-001-DW-36", price_adjustment: 0, stock: 6, is_active: true },
    ],
    created_at: "2024-02-06T00:00:00Z",
    updated_at: "2024-02-06T00:00:00Z",
  },
  {
    id: "15",
    name: "Jogger Sweatpants",
    slug: "jogger-sweatpants",
    description: "Ultra-comfortable jogger sweatpants with tapered fit. Perfect for lounging or streetwear looks.",
    price: 2999,
    compare_at_price: 3499,
    sku: "ASC-BT-002",
    is_active: true,
    category_id: "6",
    category: categories[5],
    images: [
      { id: "106", product_id: "15", url: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600", alt_text: "Jogger Sweatpants", sort_order: 0, is_primary: true },
    ],
    variants: [
      { id: "74", product_id: "15", size: "S", color: "Charcoal", sku: "ASC-BT-002-CH-S", price_adjustment: 0, stock: 15, is_active: true },
      { id: "75", product_id: "15", size: "M", color: "Charcoal", sku: "ASC-BT-002-CH-M", price_adjustment: 0, stock: 20, is_active: true },
      { id: "76", product_id: "15", size: "L", color: "Charcoal", sku: "ASC-BT-002-CH-L", price_adjustment: 0, stock: 18, is_active: true },
      { id: "77", product_id: "15", size: "XL", color: "Charcoal", sku: "ASC-BT-002-CH-XL", price_adjustment: 0, stock: 10, is_active: true },
    ],
    created_at: "2024-02-07T00:00:00Z",
    updated_at: "2024-02-07T00:00:00Z",
  },
  // NEW PRODUCTS - JACKETS
  {
    id: "16",
    name: "Bomber Jacket",
    slug: "bomber-jacket",
    description: "Classic bomber jacket with quilted lining. Ribbed cuffs and hem for a perfect fit.",
    price: 6999,
    compare_at_price: 8299,
    sku: "ASC-JK-001",
    is_active: true,
    category_id: "5",
    category: categories[4],
    images: [
      { id: "107", product_id: "16", url: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600", alt_text: "Bomber Jacket", sort_order: 0, is_primary: true },
    ],
    variants: [
      { id: "78", product_id: "16", size: "S", color: "Black", sku: "ASC-JK-001-BK-S", price_adjustment: 0, stock: 5, is_active: true },
      { id: "79", product_id: "16", size: "M", color: "Black", sku: "ASC-JK-001-BK-M", price_adjustment: 0, stock: 8, is_active: true },
      { id: "80", product_id: "16", size: "L", color: "Black", sku: "ASC-JK-001-BK-L", price_adjustment: 0, stock: 6, is_active: true },
      { id: "81", product_id: "16", size: "XL", color: "Black", sku: "ASC-JK-001-BK-XL", price_adjustment: 0, stock: 4, is_active: true },
      { id: "82", product_id: "16", size: "S", color: "Olive", sku: "ASC-JK-001-OL-S", price_adjustment: 0, stock: 4, is_active: true },
      { id: "83", product_id: "16", size: "M", color: "Olive", sku: "ASC-JK-001-OL-M", price_adjustment: 0, stock: 6, is_active: true },
      { id: "84", product_id: "16", size: "L", color: "Olive", sku: "ASC-JK-001-OL-L", price_adjustment: 0, stock: 5, is_active: true },
      { id: "85", product_id: "16", size: "XL", color: "Olive", sku: "ASC-JK-001-OL-XL", price_adjustment: 0, stock: 3, is_active: true },
    ],
    created_at: "2024-02-08T00:00:00Z",
    updated_at: "2024-02-08T00:00:00Z",
  },
  {
    id: "17",
    name: "Utility Field Jacket",
    slug: "utility-field-jacket",
    description: "Multi-pocket field jacket with water-resistant coating. Perfect for transitional weather.",
    price: 7999,
    compare_at_price: 9499,
    sku: "ASC-JK-002",
    is_active: true,
    category_id: "5",
    category: categories[4],
    images: [
      { id: "108", product_id: "17", url: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600", alt_text: "Utility Field Jacket", sort_order: 0, is_primary: true },
    ],
    variants: [
      { id: "86", product_id: "17", size: "S", color: "Black", sku: "ASC-JK-002-BK-S", price_adjustment: 0, stock: 4, is_active: true },
      { id: "87", product_id: "17", size: "M", color: "Black", sku: "ASC-JK-002-BK-M", price_adjustment: 0, stock: 6, is_active: true },
      { id: "88", product_id: "17", size: "L", color: "Black", sku: "ASC-JK-002-BK-L", price_adjustment: 0, stock: 5, is_active: true },
      { id: "89", product_id: "17", size: "XL", color: "Black", sku: "ASC-JK-002-BK-XL", price_adjustment: 0, stock: 3, is_active: true },
    ],
    created_at: "2024-02-09T00:00:00Z",
    updated_at: "2024-02-09T00:00:00Z",
  },
  // NEW PRODUCTS - HEADWEAR
  {
    id: "18",
    name: "Beanie",
    slug: "beanie",
    description: "Soft acrylic knit beanie with embroidered logo. One size fits most.",
    price: 899,
    compare_at_price: 1199,
    sku: "ASC-HW-001",
    is_active: true,
    category_id: "7",
    category: categories[6],
    images: [
      { id: "109", product_id: "18", url: "https://images.unsplash.com/photo-1576871337622-98d48d1cf531?w=600", alt_text: "Beanie", sort_order: 0, is_primary: true },
    ],
    variants: [
      { id: "90", product_id: "18", size: "One Size", color: "Black", sku: "ASC-HW-001-BK-OS", price_adjustment: 0, stock: 25, is_active: true },
      { id: "91", product_id: "18", size: "One Size", color: "Charcoal", sku: "ASC-HW-001-CH-OS", price_adjustment: 0, stock: 20, is_active: true },
      { id: "92", product_id: "18", size: "One Size", color: "Navy", sku: "ASC-HW-001-NV-OS", price_adjustment: 0, stock: 18, is_active: true },
    ],
    created_at: "2024-02-10T00:00:00Z",
    updated_at: "2024-02-10T00:00:00Z",
  },
  {
    id: "19",
    name: "Snapback Cap",
    slug: "snapback-cap",
    description: "Structured snapback cap with flat brim. Embroidered logo on front.",
    price: 1499,
    compare_at_price: 1799,
    sku: "ASC-HW-002",
    is_active: true,
    category_id: "7",
    category: categories[6],
    images: [
      { id: "110", product_id: "19", url: "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=600", alt_text: "Snapback Cap", sort_order: 0, is_primary: true },
    ],
    variants: [
      { id: "93", product_id: "19", size: "One Size", color: "Black", sku: "ASC-HW-002-BK-OS", price_adjustment: 0, stock: 22, is_active: true },
      { id: "94", product_id: "19", size: "One Size", color: "Red", sku: "ASC-HW-002-RD-OS", price_adjustment: 0, stock: 15, is_active: true },
    ],
    created_at: "2024-02-11T00:00:00Z",
    updated_at: "2024-02-11T00:00:00Z",
  },
  // NEW PRODUCTS - BAGS
  {
    id: "20",
    name: "Backpack",
    slug: "backpack",
    description: "Durable backpack with laptop compartment. Multiple pockets for organization.",
    price: 3499,
    compare_at_price: 4199,
    sku: "ASC-BG-001",
    is_active: true,
    category_id: "8",
    category: categories[7],
    images: [
      { id: "111", product_id: "20", url: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600", alt_text: "Backpack", sort_order: 0, is_primary: true },
    ],
    variants: [
      { id: "95", product_id: "20", size: "One Size", color: "Black", sku: "ASC-BG-001-BK-OS", price_adjustment: 0, stock: 12, is_active: true },
      { id: "96", product_id: "20", size: "One Size", color: "Navy", sku: "ASC-BG-001-NV-OS", price_adjustment: 0, stock: 8, is_active: true },
    ],
    created_at: "2024-02-12T00:00:00Z",
    updated_at: "2024-02-12T00:00:00Z",
  },
  {
    id: "21",
    name: "Drawstring Bag",
    slug: "drawstring-bag",
    description: "Lightweight drawstring backpack. Perfect for gym or casual outings.",
    price: 1299,
    compare_at_price: 1599,
    sku: "ASC-BG-002",
    is_active: true,
    category_id: "8",
    category: categories[7],
    images: [
      { id: "112", product_id: "21", url: "https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=600", alt_text: "Drawstring Bag", sort_order: 0, is_primary: true },
    ],
    variants: [
      { id: "97", product_id: "21", size: "One Size", color: "Black", sku: "ASC-BG-002-BK-OS", price_adjustment: 0, stock: 30, is_active: true },
      { id: "98", product_id: "21", size: "One Size", color: "White", sku: "ASC-BG-002-WH-OS", price_adjustment: 0, stock: 25, is_active: true },
    ],
    created_at: "2024-02-13T00:00:00Z",
    updated_at: "2024-02-13T00:00:00Z",
  },
  // MORE ACCESSORIES
  {
    id: "22",
    name: "Wallet",
    slug: "wallet",
    description: "Minimalist bi-fold wallet with RFID blocking. Premium leather construction.",
    price: 1799,
    compare_at_price: 2199,
    sku: "ASC-AC-003",
    is_active: true,
    category_id: "4",
    category: categories[3],
    images: [
      { id: "113", product_id: "22", url: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=600", alt_text: "Wallet", sort_order: 0, is_primary: true },
    ],
    variants: [
      { id: "99", product_id: "22", size: "One Size", color: "Black", sku: "ASC-AC-003-BK-OS", price_adjustment: 0, stock: 18, is_active: true },
      { id: "100", product_id: "22", size: "One Size", color: "Brown", sku: "ASC-AC-003-BR-OS", price_adjustment: 0, stock: 15, is_active: true },
    ],
    created_at: "2024-02-14T00:00:00Z",
    updated_at: "2024-02-14T00:00:00Z",
  },
  {
    id: "23",
    name: "Sunglasses",
    slug: "sunglasses",
    description: "Classic aviator sunglasses with UV400 protection. Metal frame with adjustable nose pads.",
    price: 2499,
    compare_at_price: 2999,
    sku: "ASC-AC-004",
    is_active: true,
    category_id: "4",
    category: categories[3],
    images: [
      { id: "114", product_id: "23", url: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600", alt_text: "Sunglasses", sort_order: 0, is_primary: true },
    ],
    variants: [
      { id: "101", product_id: "23", size: "One Size", color: "Gold", sku: "ASC-AC-004-GD-OS", price_adjustment: 0, stock: 12, is_active: true },
      { id: "102", product_id: "23", size: "One Size", color: "Silver", sku: "ASC-AC-004-SV-OS", price_adjustment: 0, stock: 10, is_active: true },
    ],
    created_at: "2024-02-15T00:00:00Z",
    updated_at: "2024-02-15T00:00:00Z",
  },
  {
    id: "24",
    name: "Wristwatch",
    slug: "wristwatch",
    description: "Minimalist analog watch with leather strap. Japanese quartz movement.",
    price: 4999,
    compare_at_price: 5999,
    sku: "ASC-AC-005",
    is_active: true,
    category_id: "4",
    category: categories[3],
    images: [
      { id: "115", product_id: "24", url: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=600", alt_text: "Wristwatch", sort_order: 0, is_primary: true },
    ],
    variants: [
      { id: "103", product_id: "24", size: "One Size", color: "Black", sku: "ASC-AC-005-BK-OS", price_adjustment: 0, stock: 8, is_active: true },
      { id: "104", product_id: "24", size: "One Size", color: "Brown", sku: "ASC-AC-005-BR-OS", price_adjustment: 0, stock: 6, is_active: true },
    ],
    created_at: "2024-02-16T00:00:00Z",
    updated_at: "2024-02-16T00:00:00Z",
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(categorySlug: string): Product[] {
  return products.filter((p) => p.category?.slug === categorySlug);
}

export function searchProducts(query: string): Product[] {
  const lowerQuery = query.toLowerCase();
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(lowerQuery) ||
      p.description?.toLowerCase().includes(lowerQuery) ||
      p.category?.name.toLowerCase().includes(lowerQuery)
  );
}

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    minimumFractionDigits: 0,
  }).format(price);
}
